#!/usr/bin/env bash
set -euo pipefail

# Designed to be called on startup (e.g. from cloud-init) depending on the function
# like this:
# /cms_init cms
# /cms_init cws
# /cms_init worker

_hyperthreading() {
    # Disabling hyperthreading
    for cpunum in $(
        cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list |
        cut -s -d, -f2- | tr ',' '\n' | sort -un); do
            echo 0 > /sys/devices/system/cpu/cpu$cpunum/online
    done

    # Adjust number of workers to be number of CPUs
    sed -i "s/numprocs=.*/numprocs=$(nproc)/" /etc/supervisor/conf.d/worker.conf
}

_worker_cms_conf() {
    sed -i -e 's/worker4.cms1/127.0.0.1/g' \
           -e '/worker.\.cms1/d' /usr/local/etc/cms.conf
}

case "$1" in
    worker)
        _hyperthreading
        _worker_cms_conf
        ;; 
    cms)
        :
esac

sed -i 's/autostart=false/autostart=true/' /etc/supervisor/conf.d/${1}.conf
supervisorctl reload || :
