#!/usr/bin/env bash
set -euo pipefail

# Designed to be called on startup (e.g. from cloud-init) depending on the function
# like this:
# /cms_init centriukas
# /cms_init cws
# /cms_init worker

# Give default AWS/debian user access to cms logs/etc.
usermod -aG cmsuser admin

_hyperthreading() {
    # Disabling hyperthreading
    for cpunum in $(
        cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list |
        cut -s -d, -f2- | tr ',' '\n' | sort -un); do
            echo 0 > /sys/devices/system/cpu/cpu$cpunum/online
    done

}

_set_workers() {
    # Adjust number of workers to be number of CPUs
    sed -i "s/numprocs=.*/numprocs=$1/" /etc/supervisor/conf.d/worker.conf
}

_set_static_cpufreq() {
    # hardcoding 2.4ghz which matches c7i.24xlarge base clock.
    # TODO: fix this to be autodetected
    echo passive > /sys/devices/system/cpu/intel_pstate/status
    echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
    echo 100 > /sys/devices/system/cpu/intel_pstate/min_perf_pct
    cpupower frequency-set -d 2.4GHz -u 2.4GHz -g performance
}

_disable_transparent_hugepages() {
    echo madvise > /sys/kernel/mm/transparent_hugepage/enabled
    echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
}

_enable() {
    sed -i 's/autostart=false/autostart=true/' /etc/supervisor/conf.d/${1}.conf
}

case "$1" in
    worker)
        _hyperthreading
        # Adjust number of workers to be number of CPUs
        _set_workers $(nproc)
        _disable_transparent_hugepages
        _enable worker
        ;; 
    big-worker)
        _hyperthreading
        _set_workers 20
        _disable_transparent_hugepages
        _set_static_cpufreq
        _enable worker
        ;; 
    centriukas)
        _enable centriukas
        _enable cws
        ;;
    cws)
        _enable cws
        echo '*/30 8-16 * * * cmsuser /usr/local/bin/cmsSendLogs' > /etc/cron.d/periodicCmsSendLogs
        ;;
    rws)
        _enable rws
	;;
esac

supervisorctl reload || :
