[program:cmsLogService]
command=/usr/local/lib/pyenv/shims/cmsLogService 0
user=cmsuser
autostart=false
environment=CMS_CONFIG=/usr/local/etc/cms_centriukas.conf

[program:cmsResourceService]
command=/usr/local/lib/pyenv/shims/cmsResourceService -a ALL 0
user=cmsuser
stopasgroup=true
autostart=false
environment=CMS_CONFIG=/usr/local/etc/cms_centriukas.conf
