[program:cmsContestWebServer-test-jau]
command=/usr/local/lib/pyenv/shims/cmsContestWebServer -c 3 4
user=cmsuser
autostart=false
environment=CMS_CONFIG=/usr/local/etc/cms_main.conf

[program:cmsContestWebServer-test-vyr]
command=/usr/local/lib/pyenv/shims/cmsContestWebServer -c 4 5
user=cmsuser
autostart=false
environment=CMS_CONFIG=/usr/local/etc/cms_main.conf
