[program:cmsContestWebServer-jau]
command=/usr/local/lib/pyenv/shim/cmsContestWebServer -c 1 0
user=cmsuser
autostart=false
environment=CMS_CONFIG=/usr/local/etc/cms_main.conf

[program:cmsContestWebServer-vyr]
command=/usr/local/lib/pyenv/shims/cmsContestWebServer -c 2 1
user=cmsuser
autostart=false
environment=CMS_CONFIG=/usr/local/etc/cms_main.conf
