[program:cmsRankingWebServer-jau]
command=/usr/local/lib/pyenv/shims/cmsRankingWebServer --config=/usr/local/etc/rws-jau.conf
user=cmsuser
autostart=false

[program:cmsRankingWebServer-vyr]
command=/usr/local/lib/pyenv/shims/cmsRankingWebServer --config=/usr/local/etc/rws-vyr.conf
user=cmsuser
autostart=false

[program:cmsRankingWebServer-jau-pub]
command=/usr/local/lib/pyenv/shims/cmsRankingWebServer --config=/usr/local/etc/rws-jau-pub.conf
user=cmsuser
autostart=false

[program:cmsRankingWebServer-vyr-pub]
command=/usr/local/lib/pyenv/shims/cmsRankingWebServer --config=/usr/local/etc/rws-vyr-pub.conf
user=cmsuser
autostart=false
