#!/usr/bin/env bash
set -euo pipefail

# Create an AMI which will be either:
# 1. Worker
# 2. CWS
# 3. Centriukas ("central" server)
#
# The AMI will be the clone of the current one (unless AMI_ID is overriden).
# This script downloads CMS, builds a deb package, and creates an AMI out of it.
#
# Also in the deb package:
# * Create /etc/supervisord/{cws,worker,centriukas}.conf
# * Create /cms_{cms,worker,centriukas}, which:
# ** Create relevant ~/cms.conf
# ** On Worker, disable hyperthreading.
# ** Start relevant supervisor processes

# If you want to base off something other than current AMI, set AMI_ID.
AMI_ID=${AMI_ID:-$(curl http://169.254.169.254/latest/meta-data/ami-id)}

GIT_CMS="git://github.com/lmio/cms.git -b lmio2015 --recursive"

DEPENDENCIES=$(paste -sd' ' - -  <<EOF
fpc postgresql-client gettext python2.7 python-setuptools python-tornado
python-psycopg2 python-sqlalchemy python-psutil python-netifaces python-crypto
python-tz python-six iso-codes shared-mime-info stl-manual python-beautifulsoup
python-mechanize python-coverage python-mock cgroup-lite python-requests
python-werkzeug python-gevent python-yaml python-sphinx
EOF
)
DEPENDENCIES=${DEPENDENCIES// /,}

_download_cms() {
    git clone $GIT_CMS
    cd cms && ./setup.py build && cd ..
}

_checkinstall() {
    cd cms
    echo 'Contest Management System, LMIO2015 version' > description-pak
    sudo checkinstall -y --install=no \
        --exclude ${PWD},/etc,/var \
        --requires $DEPENDENCIES \
        ./setup.py install
    cd ..
}

#dpkg-deb -R cms_20160103-1_amd64.deb tmp
#cat <<EOF > tmp/DEBIAN/postinst
##!/bin/sh
#set -e
#ISOLATE=/usr/local/bin/isolate
#
#chmod 755 $ISOLATE
#chown root:root $ISOLATE
#chmod +s $ISOLATE
#EOF
#
#dpkg-deb -b tmp fixed.deb
#
#aminate -e ec2_aptitude_linux -B ami-47a23a30 -r eu-west-1 --partition 1 --vm-type hvm http://172.31.36.243:8000/cms_20160103-1_amd64.deb
